package com.redhat.jboss.hr.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(b6604d93d2a928b60e0003d979de0f7c)
 */
@org.kie.api.definition.type.Label(value = "Address")
public class Address extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "address")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String address;
    
    @org.kie.api.definition.type.Label(value = "City")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String city;
    
    @org.kie.api.definition.type.Label(value = "Country")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String country;
    
    @org.kie.api.definition.type.Label(value = "ZIP Code")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String zip;

    public Address() {
    }

    public Address(java.lang.String address, java.lang.String city, java.lang.String zip, java.lang.String country) {
        this.address = address;
        this.city = city;
        this.zip = zip;
        this.country = country;
    }


    
    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.String getCity() {
        return this.city;
    }

    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.String getCountry() {
        return this.country;
    }

    public void setCountry(java.lang.String country) {
        this.country = country;
    }
    
    public java.lang.String getZip() {
        return this.zip;
    }

    public void setZip(java.lang.String zip) {
        this.zip = zip;
    }
}