package com.redhat.jboss.hr.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(6dd48a4af99e254bc77e57aba3160638)
 */
@org.kie.api.definition.type.Label(value = "Customer")
public class Customer extends java.lang.Object implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "AcquistionDate")
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date acquistionDate;
    
    @org.kie.api.definition.type.Label(value = "Address")
    @org.kie.api.definition.type.Position(value = 3)
    private com.redhat.jboss.hr.rewards.Address address;
    
    @org.kie.api.definition.type.Label(value = "Customer Code")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String customerCode;
    
    @org.kie.api.definition.type.Label(value = "CustomerType")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String customerType;
    
    @org.kie.api.definition.type.Label(value = "Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String name;

    public Customer() {
    }

    public Customer(java.lang.String name, java.lang.String customerCode, java.util.Date acquistionDate, com.redhat.jboss.hr.rewards.Address address, java.lang.String customerType) {
        this.name = name;
        this.customerCode = customerCode;
        this.acquistionDate = acquistionDate;
        this.address = address;
        this.customerType = customerType;
    }


    
    public java.util.Date getAcquistionDate() {
        return this.acquistionDate;
    }

    public void setAcquistionDate(java.util.Date acquistionDate) {
        this.acquistionDate = acquistionDate;
    }
    
    public com.redhat.jboss.hr.rewards.Address getAddress() {
        return this.address;
    }

    public void setAddress(com.redhat.jboss.hr.rewards.Address address) {
        this.address = address;
    }
    
    public java.lang.String getCustomerCode() {
        return this.customerCode;
    }

    public void setCustomerCode(java.lang.String customerCode) {
        this.customerCode = customerCode;
    }
    
    public java.lang.String getCustomerType() {
        return this.customerType;
    }

    public void setCustomerType(java.lang.String customerType) {
        this.customerType = customerType;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }
}