package com.redhat.jboss.hr.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(947efb6e7af1a169c0cf83d7b63da260)
 */
@org.kie.api.definition.type.Label(value = "Customer")
public class Customer  implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    @org.kie.api.definition.type.Label(value = "AcquistionDate")
    @org.kie.api.definition.type.Position(value = 0)
    private java.util.Date acquistionDate;
    
    @org.kie.api.definition.type.Label(value = "Address")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String address;
    
    @org.kie.api.definition.type.Label(value = "CustomerCode")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String customerCode;
    
    @org.kie.api.definition.type.Label(value = "CustomerType")
    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.String customerType;
    
    @org.kie.api.definition.type.Label(value = "Name")
    @org.kie.api.definition.type.Position(value = 4)
    private java.lang.String name;

    public Customer() {
    }

    public Customer(java.util.Date acquistionDate, java.lang.String address, java.lang.String customerCode, java.lang.String customerType, java.lang.String name) {
        this.acquistionDate = acquistionDate;
        this.address = address;
        this.customerCode = customerCode;
        this.customerType = customerType;
        this.name = name;
    }


    
    public java.util.Date getAcquistionDate() {
        return this.acquistionDate;
    }

    public void setAcquistionDate(java.util.Date acquistionDate) {
        this.acquistionDate = acquistionDate;
    }
    
    public java.lang.String getAddress() {
        return this.address;
    }

    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public java.lang.String getCustomerCode() {
        return this.customerCode;
    }

    public void setCustomerCode(java.lang.String customerCode) {
        this.customerCode = customerCode;
    }
    
    public java.lang.String getCustomerType() {
        return this.customerType;
    }

    public void setCustomerType(java.lang.String customerType) {
        this.customerType = customerType;
    }
    
    public java.lang.String getName() {
        return this.name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }
}